### ISSUE TITLE
请教下dockerfile的问题

### ISSUE THREAD

**Issue by q123458384** [SuperNG6/Docker-qBittorrent-Enhanced-Edition#4]
你好，看你的镜像是dockerhub连接github自动构建的，我用dockerhub的自动构建只有amd64的镜像。想请问这种自动构建别的平台的镜像要怎么操作，百度没找到参考。先谢谢了

**Comment by SuperNG6** [comment]
我的博客里搜 sleele.com “GitHub action”，写过这方面的教程

crosscc <notifications@github.com>于2020年5月20日 周三下午1:04写道：

**Comment by q123458384** [comment]
> GitHub

。好神奇~~~我原来看的教程就是你的github action，之前用的是可以的，最近那个action脚本的作者更新了ilteoood/docker_buildx，自动构建的时候提示
```
Command failed: docker_buildx/scripts/docker_build.sh linux/arm64,linux/amd64 ***/***v2.2,latest Dockerfile true none false 
```
然后我就想到dockerhub也可以同步github脚本自动构建(https://hub.docker.com/repository/create)，试了一下只有amd64镜像~看你的镜像有全平台的 就来问一下。。

**Comment by SuperNG6** [comment]
不清楚。可以看看源码改哪了，或者fork之前的commit
在 2020年5月20日 +0800 PM1:54，crosscc <notifications@github.com>，写道：

**Comment by SuperNG6** [comment]
还真的挂了，回退老版本也不行
参照我这个改吧，比ilteoood/docker_buildx的要复杂，用这个的一般都是大项目，很稳定
````
name: Build Image
on:
  push:
    branches:
      - 'master'      
    paths-ignore:
      - README.md
  schedule:
    - cron: 0 8 * * 1

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Dockerhub login
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
      - name: Build dockerfile (with push)
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker buildx build \
          --platform=linux/amd64,linux/arm/v7,linux/arm64 \
          --output "type=image,push=true" \
          --file ./Dockerfile . \
          --tag superng6/qbittorrent:latest
````
