### ISSUE TITLE
PUID和PGID传入好像不起作用

### ISSUE THREAD

**Issue by zzcabc** [SuperNG6/Docker-qBittorrent-Enhanced-Edition#53]
docker-compose如下，指定PUID和PGID分别是1000和100，在启动容器时，下载文件夹会变成 `drwxr-sr-x+ 25       911  1001 16384 Apr  8 17:41 qbittorrent-downloads`

```yml  
qbittorrent:
    image: superng6/qbittorrentee
    container_name: qbittorrentee
    restart: unless-stopped
    network_mode: host
    logging:
      options:
        max-size: "1m"
    environment:
      - PUID=1000
      - PGID=100
      - TZ=${TZ}
```

**Comment by licia-tia** [comment]
同样问题复现

**Comment by 1298345095** [comment]
+1

**Comment by 1298345095** [comment]
umask同样不生效

**Comment by PlayerYao** [comment]
umask不生效, 这对unraid有影响. 在Unraid系统里, docker这里的用户常用的是nobody, nobody用户是user用户组, 共享文件夹的用户组也是user组, 但是qbee默认umask是022导致创建的文件变成644, 共享文件夹的用户只能查看不能编辑

**Comment by PlayerYao** [comment]
> umask同样不生效

+1, 顺便一提umask可以用UMASK_SET变量

**Comment by PillarsZhang** [comment]
多尝试下会发现，stop 之后直接 up，权限又会被正确设置
只有 down 后再 up，才会出现 911
我猜测是它结合 s6 overlay 或 linuxserver 逻辑有点问题，用户创建滞后了（而 stop 再 up 用户已经创建在容器里

但是目前的 [linuxserver](https://github.com/linuxserver/docker-qbittorrent) 最新原版是没问题的，最佳解决方案是重新移植一遍
**直接的解决方案，把 `root/etc/cont-init.d/30-config` 里面的 chown 删了，手动改一次权限就好**

比较奇怪的是同样被 chown 的 `config` 不会出现 911，这解释不通

**Comment by SuperNG6** [comment]
> 多尝试下会发现，stop 之后直接 up，权限又会被正确设置 只有 down 后再 up，才会出现 911 我猜测是它结合 s6 overlay 或 linuxserver 逻辑有点问题，用户创建滞后了（而 stop 再 up 用户已经创建在容器里
> 
> 但是目前的 [linuxserver](https://github.com/linuxserver/docker-qbittorrent) 最新原版是没问题的，最佳解决方案是重新移植一遍 **直接的解决方案，把 `root/etc/cont-init.d/30-config` 里面的 chown 删了，手动改一次权限就好**
> 
> 比较奇怪的是同样被 chown 的 `config` 不会出现 911，这解释不通

可能是老版本的 inuxserver base image 有问题，已经更新到最新版，可以尝试一下看看，目前我这边无法复现这个问题

**Comment by PillarsZhang** [comment]
还是一样的问题
zhang:zhang 即 1000:1000
```yaml
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config:/config
      - ./downloads:/downloads
```
但我挂载的目录是软链接 `downloads -> /mnt/WD-A1T/download/qBittorrentEE`
正常应该`drwxrwxr-x 1   zhang zhang 2.5K Sep 14 23:21 qBittorrentEE`
第一次`docker compose up`会变成`drwxrwxr-x 1   911 zhang 2.5K Sep 14 23:21 qBittorrentEE`
常规情况是怎么样就不知道了
