### ISSUE TITLE
容器启动初始化时无视权限而直接修改，导致在无根容器主机中提示无权

### ISSUE THREAD

**Issue by Gloryandel** [SuperNG6/Docker-qBittorrent-Enhanced-Edition#70]
Podman 无根容器中强制修改目录权限，希望略微做适配
![image](https://github.com/user-attachments/assets/4520a2bd-6968-4706-8499-ac215f3a27e7)

容器内部权限是对应统一的 root，在无根容器中反而不需要修改
![image](https://github.com/user-attachments/assets/623cab62-787c-46bb-8dc5-162170f0892e)

**Comment by Gloryandel** [comment]
```
services:
  qbittorrentee:
    image: superng6/qbittorrentee:latest
    container_name: qbittorrentee
    hostname: Arc
    ports:
      - 8080:8080 # WebUI
      - 6881:6881
      - 6881:6881/udp
    volumes:
       - ./config:/config
       - ./downloads:/downloads
    environment:
      - TZ=Asia/Shanghai
      - PUID=0
      - PGID=0
    restart: unless-stopped
```
无根容器反而希望以 root 运行，如果无 PUID 和 PGID 时默认以 root 就很好
