### ISSUE TITLE
升级5.0.3.10后打不开webUI了，貌似也没启动成功

### ISSUE THREAD

**Issue by lxw314** [SuperNG6/Docker-qBittorrent-Enhanced-Edition#87]
之前一直很正常，今天升级5.0.3.10后打不开webUI页面了，日志也变得不正常了：
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
```
过几分钟会听见机械硬盘炒豆子，容器一停就没了
truenas记录如图，不知道在干啥
![Image](https://github.com/user-attachments/assets/465995e5-e96f-4976-a4e5-55cff9091774)

退回5.0.2.10又正常了，不清楚是哪里出了问题，附个compose：
```
version: "2"
networks:
  lxw-network:
    external: true
services:
  qbittorrentee:
    image: superng6/qbittorrentee:5.0.3.10
    container_name: qbit-ee
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - /mnt/docker/qbit-ee/config:/config
      - /mnt/anime:/downloads
    networks: 
      - lxw-network
    ports:
      - 36767:6881
      - 36767:6881/udp
      - 38081:8080
    restart: unless-stopped
```
